# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- test

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  data: "$(hello from devops team)"

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: 
      name: default
      # vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/dotnet_webapi/Dockerfile'
        tags: |
          $(tag)
    - script: |
        cd unit-testing
        dotnet test
        echo "this is mydemo"
        echo ":this is the second command"
    - script: echo "this is another command"